var tree = [["Twig",,"",
                [["Error",,"",
                [["Loader","Twig_Error_Loader.html"," < Twig_Error",
                [        ]],["Runtime","Twig_Error_Runtime.html"," < Twig_Error",
                [        ]],["Syntax","Twig_Error_Syntax.html"," < Twig_Error",
                [        ]]        ]],["Extension",,"",
                [["Core","Twig_Extension_Core.html"," < Twig_Extension",
                [        ]],["Debug","Twig_Extension_Debug.html"," < Twig_Extension",
                [        ]],["Escaper","Twig_Extension_Escaper.html"," < Twig_Extension",
                [        ]],["Optimizer","Twig_Extension_Optimizer.html"," < Twig_Extension",
                [        ]],["Sandbox","Twig_Extension_Sandbox.html"," < Twig_Extension",
                [        ]],["Staging","Twig_Extension_Staging.html"," < Twig_Extension",
                [        ]],["StringLoader","Twig_Extension_StringLoader.html"," < Twig_Extension",
                [        ]]        ]],["Filter",,"",
                [["Function","Twig_Filter_Function.html"," < Twig_Filter",
                [        ]],["Method","Twig_Filter_Method.html"," < Twig_Filter",
                [        ]],["Node","Twig_Filter_Node.html"," < Twig_Filter",
                [        ]]        ]],["Function",,"",
                [["Function","Twig_Function_Function.html"," < Twig_Function",
                [        ]],["Method","Twig_Function_Method.html"," < Twig_Function",
                [        ]],["Node","Twig_Function_Node.html"," < Twig_Function",
                [        ]]        ]],["Loader",,"",
                [["Array","Twig_Loader_Array.html","",
                [        ]],["Chain","Twig_Loader_Chain.html","",
                [        ]],["Filesystem","Twig_Loader_Filesystem.html","",
                [        ]],["String","Twig_Loader_String.html","",
                [        ]]        ]],["Node",,"",
                [["Expression",,"",
                [["Binary",,"",
                [["Add","Twig_Node_Expression_Binary_Add.html"," < Twig_Node_Expression_Binary",
                [        ]],["And","Twig_Node_Expression_Binary_And.html"," < Twig_Node_Expression_Binary",
                [        ]],["BitwiseAnd","Twig_Node_Expression_Binary_BitwiseAnd.html"," < Twig_Node_Expression_Binary",
                [        ]],["BitwiseOr","Twig_Node_Expression_Binary_BitwiseOr.html"," < Twig_Node_Expression_Binary",
                [        ]],["BitwiseXor","Twig_Node_Expression_Binary_BitwiseXor.html"," < Twig_Node_Expression_Binary",
                [        ]],["Concat","Twig_Node_Expression_Binary_Concat.html"," < Twig_Node_Expression_Binary",
                [        ]],["Div","Twig_Node_Expression_Binary_Div.html"," < Twig_Node_Expression_Binary",
                [        ]],["Equal","Twig_Node_Expression_Binary_Equal.html"," < Twig_Node_Expression_Binary",
                [        ]],["FloorDiv","Twig_Node_Expression_Binary_FloorDiv.html"," < Twig_Node_Expression_Binary",
                [        ]],["Greater","Twig_Node_Expression_Binary_Greater.html"," < Twig_Node_Expression_Binary",
                [        ]],["GreaterEqual","Twig_Node_Expression_Binary_GreaterEqual.html"," < Twig_Node_Expression_Binary",
                [        ]],["In","Twig_Node_Expression_Binary_In.html"," < Twig_Node_Expression_Binary",
                [        ]],["Less","Twig_Node_Expression_Binary_Less.html"," < Twig_Node_Expression_Binary",
                [        ]],["LessEqual","Twig_Node_Expression_Binary_LessEqual.html"," < Twig_Node_Expression_Binary",
                [        ]],["Mod","Twig_Node_Expression_Binary_Mod.html"," < Twig_Node_Expression_Binary",
                [        ]],["Mul","Twig_Node_Expression_Binary_Mul.html"," < Twig_Node_Expression_Binary",
                [        ]],["NotEqual","Twig_Node_Expression_Binary_NotEqual.html"," < Twig_Node_Expression_Binary",
                [        ]],["NotIn","Twig_Node_Expression_Binary_NotIn.html"," < Twig_Node_Expression_Binary",
                [        ]],["Or","Twig_Node_Expression_Binary_Or.html"," < Twig_Node_Expression_Binary",
                [        ]],["Power","Twig_Node_Expression_Binary_Power.html"," < Twig_Node_Expression_Binary",
                [        ]],["Range","Twig_Node_Expression_Binary_Range.html"," < Twig_Node_Expression_Binary",
                [        ]],["Sub","Twig_Node_Expression_Binary_Sub.html"," < Twig_Node_Expression_Binary",
                [        ]]        ]],["Filter",,"",
                [["Default","Twig_Node_Expression_Filter_Default.html"," < Twig_Node_Expression_Filter",
                [        ]]        ]],["Test",,"",
                [["Constant","Twig_Node_Expression_Test_Constant.html"," < Twig_Node_Expression_Test",
                [        ]],["Defined","Twig_Node_Expression_Test_Defined.html"," < Twig_Node_Expression_Test",
                [        ]],["Divisibleby","Twig_Node_Expression_Test_Divisibleby.html"," < Twig_Node_Expression_Test",
                [        ]],["Even","Twig_Node_Expression_Test_Even.html"," < Twig_Node_Expression_Test",
                [        ]],["Null","Twig_Node_Expression_Test_Null.html"," < Twig_Node_Expression_Test",
                [        ]],["Odd","Twig_Node_Expression_Test_Odd.html"," < Twig_Node_Expression_Test",
                [        ]],["Sameas","Twig_Node_Expression_Test_Sameas.html"," < Twig_Node_Expression_Test",
                [        ]]        ]],["Unary",,"",
                [["Neg","Twig_Node_Expression_Unary_Neg.html"," < Twig_Node_Expression_Unary",
                [        ]],["Not","Twig_Node_Expression_Unary_Not.html"," < Twig_Node_Expression_Unary",
                [        ]],["Pos","Twig_Node_Expression_Unary_Pos.html"," < Twig_Node_Expression_Unary",
                [        ]]        ]],["Array","Twig_Node_Expression_Array.html"," < Twig_Node_Expression",
                [        ]],["AssignName","Twig_Node_Expression_AssignName.html"," < Twig_Node_Expression_Name",
                [        ]],["Binary","Twig_Node_Expression_Binary.html"," < Twig_Node_Expression",
                [        ]],["BlockReference","Twig_Node_Expression_BlockReference.html"," < Twig_Node_Expression",
                [        ]],["Call","Twig_Node_Expression_Call.html"," < Twig_Node_Expression",
                [        ]],["Conditional","Twig_Node_Expression_Conditional.html"," < Twig_Node_Expression",
                [        ]],["Constant","Twig_Node_Expression_Constant.html"," < Twig_Node_Expression",
                [        ]],["ExtensionReference","Twig_Node_Expression_ExtensionReference.html"," < Twig_Node_Expression",
                [        ]],["Filter","Twig_Node_Expression_Filter.html"," < Twig_Node_Expression_Call",
                [        ]],["Function","Twig_Node_Expression_Function.html"," < Twig_Node_Expression_Call",
                [        ]],["GetAttr","Twig_Node_Expression_GetAttr.html"," < Twig_Node_Expression",
                [        ]],["MethodCall","Twig_Node_Expression_MethodCall.html"," < Twig_Node_Expression",
                [        ]],["Name","Twig_Node_Expression_Name.html"," < Twig_Node_Expression",
                [        ]],["Parent","Twig_Node_Expression_Parent.html"," < Twig_Node_Expression",
                [        ]],["TempName","Twig_Node_Expression_TempName.html"," < Twig_Node_Expression",
                [        ]],["Test","Twig_Node_Expression_Test.html"," < Twig_Node_Expression_Call",
                [        ]],["Unary","Twig_Node_Expression_Unary.html"," < Twig_Node_Expression",
                [        ]]        ]],["AutoEscape","Twig_Node_AutoEscape.html"," < Twig_Node",
                [        ]],["Block","Twig_Node_Block.html"," < Twig_Node",
                [        ]],["BlockReference","Twig_Node_BlockReference.html"," < Twig_Node",
                [        ]],["Body","Twig_Node_Body.html"," < Twig_Node",
                [        ]],["Do","Twig_Node_Do.html"," < Twig_Node",
                [        ]],["Embed","Twig_Node_Embed.html"," < Twig_Node_Include",
                [        ]],["Expression","Twig_Node_Expression.html"," < Twig_Node",
                [        ]],["Flush","Twig_Node_Flush.html"," < Twig_Node",
                [        ]],["For","Twig_Node_For.html"," < Twig_Node",
                [        ]],["ForLoop","Twig_Node_ForLoop.html"," < Twig_Node",
                [        ]],["If","Twig_Node_If.html"," < Twig_Node",
                [        ]],["Import","Twig_Node_Import.html"," < Twig_Node",
                [        ]],["Include","Twig_Node_Include.html"," < Twig_Node",
                [        ]],["Macro","Twig_Node_Macro.html"," < Twig_Node",
                [        ]],["Module","Twig_Node_Module.html"," < Twig_Node",
                [        ]],["Print","Twig_Node_Print.html"," < Twig_Node",
                [        ]],["Sandbox","Twig_Node_Sandbox.html"," < Twig_Node",
                [        ]],["SandboxedModule","Twig_Node_SandboxedModule.html"," < Twig_Node_Module",
                [        ]],["SandboxedPrint","Twig_Node_SandboxedPrint.html"," < Twig_Node_Print",
                [        ]],["Set","Twig_Node_Set.html"," < Twig_Node",
                [        ]],["SetTemp","Twig_Node_SetTemp.html"," < Twig_Node",
                [        ]],["Spaceless","Twig_Node_Spaceless.html"," < Twig_Node",
                [        ]],["Text","Twig_Node_Text.html"," < Twig_Node",
                [        ]]        ]],["NodeVisitor",,"",
                [["Escaper","Twig_NodeVisitor_Escaper.html","",
                [        ]],["Optimizer","Twig_NodeVisitor_Optimizer.html","",
                [        ]],["SafeAnalysis","Twig_NodeVisitor_SafeAnalysis.html","",
                [        ]],["Sandbox","Twig_NodeVisitor_Sandbox.html","",
                [        ]]        ]],["Sandbox",,"",
                [["SecurityError","Twig_Sandbox_SecurityError.html"," < Twig_Error",
                [        ]],["SecurityPolicy","Twig_Sandbox_SecurityPolicy.html","",
                [        ]],["SecurityPolicyInterface","Twig_Sandbox_SecurityPolicyInterface.html","",
                [        ]]        ]],["Test",,"",
                [["Function","Twig_Test_Function.html"," < Twig_Test",
                [        ]],["IntegrationTestCase","Twig_Test_IntegrationTestCase.html"," < PHPUnit_Framework_TestCase",
                [        ]],["Method","Twig_Test_Method.html"," < Twig_Test",
                [        ]],["Node","Twig_Test_Node.html"," < Twig_Test",
                [        ]],["NodeTestCase","Twig_Test_NodeTestCase.html"," < PHPUnit_Framework_TestCase",
                [        ]]        ]],["TokenParser",,"",
                [["AutoEscape","Twig_TokenParser_AutoEscape.html"," < Twig_TokenParser",
                [        ]],["Block","Twig_TokenParser_Block.html"," < Twig_TokenParser",
                [        ]],["Do","Twig_TokenParser_Do.html"," < Twig_TokenParser",
                [        ]],["Embed","Twig_TokenParser_Embed.html"," < Twig_TokenParser_Include",
                [        ]],["Extends","Twig_TokenParser_Extends.html"," < Twig_TokenParser",
                [        ]],["Filter","Twig_TokenParser_Filter.html"," < Twig_TokenParser",
                [        ]],["Flush","Twig_TokenParser_Flush.html"," < Twig_TokenParser",
                [        ]],["For","Twig_TokenParser_For.html"," < Twig_TokenParser",
                [        ]],["From","Twig_TokenParser_From.html"," < Twig_TokenParser",
                [        ]],["If","Twig_TokenParser_If.html"," < Twig_TokenParser",
                [        ]],["Import","Twig_TokenParser_Import.html"," < Twig_TokenParser",
                [        ]],["Include","Twig_TokenParser_Include.html"," < Twig_TokenParser",
                [        ]],["Macro","Twig_TokenParser_Macro.html"," < Twig_TokenParser",
                [        ]],["Sandbox","Twig_TokenParser_Sandbox.html"," < Twig_TokenParser",
                [        ]],["Set","Twig_TokenParser_Set.html"," < Twig_TokenParser",
                [        ]],["Spaceless","Twig_TokenParser_Spaceless.html"," < Twig_TokenParser",
                [        ]],["Use","Twig_TokenParser_Use.html"," < Twig_TokenParser",
                [        ]]        ]],["Autoloader","Twig_Autoloader.html","",
                [        ]],["Compiler","Twig_Compiler.html","",
                [        ]],["CompilerInterface","Twig_CompilerInterface.html","",
                [        ]],["Environment","Twig_Environment.html","",
                [        ]],["Error","Twig_Error.html"," < Exception",
                [        ]],["ExistsLoaderInterface","Twig_ExistsLoaderInterface.html","",
                [        ]],["ExpressionParser","Twig_ExpressionParser.html","",
                [        ]],["Extension","Twig_Extension.html","",
                [        ]],["ExtensionInterface","Twig_ExtensionInterface.html","",
                [        ]],["Filter","Twig_Filter.html","",
                [        ]],["FilterCallableInterface","Twig_FilterCallableInterface.html","",
                [        ]],["FilterInterface","Twig_FilterInterface.html","",
                [        ]],["Function","Twig_Function.html","",
                [        ]],["FunctionCallableInterface","Twig_FunctionCallableInterface.html","",
                [        ]],["FunctionInterface","Twig_FunctionInterface.html","",
                [        ]],["Lexer","Twig_Lexer.html","",
                [        ]],["LexerInterface","Twig_LexerInterface.html","",
                [        ]],["LoaderInterface","Twig_LoaderInterface.html","",
                [        ]],["Markup","Twig_Markup.html","",
                [        ]],["Node","Twig_Node.html","",
                [        ]],["NodeInterface","Twig_NodeInterface.html","",
                [        ]],["NodeOutputInterface","Twig_NodeOutputInterface.html","",
                [        ]],["NodeTraverser","Twig_NodeTraverser.html","",
                [        ]],["NodeVisitorInterface","Twig_NodeVisitorInterface.html","",
                [        ]],["Parser","Twig_Parser.html","",
                [        ]],["ParserInterface","Twig_ParserInterface.html","",
                [        ]],["SimpleFilter","Twig_SimpleFilter.html","",
                [        ]],["SimpleFunction","Twig_SimpleFunction.html","",
                [        ]],["SimpleTest","Twig_SimpleTest.html","",
                [        ]],["Template","Twig_Template.html","",
                [        ]],["TemplateInterface","Twig_TemplateInterface.html","",
                [        ]],["Test","Twig_Test.html","",
                [        ]],["TestCallableInterface","Twig_TestCallableInterface.html","",
                [        ]],["TestInterface","Twig_TestInterface.html","",
                [        ]],["Token","Twig_Token.html","",
                [        ]],["TokenParser","Twig_TokenParser.html","",
                [        ]],["TokenParserBroker","Twig_TokenParserBroker.html","",
                [        ]],["TokenParserBrokerInterface","Twig_TokenParserBrokerInterface.html","",
                [        ]],["TokenParserInterface","Twig_TokenParserInterface.html","",
                [        ]],["TokenStream","Twig_TokenStream.html","",
                [        ]]        ]]        ]

